import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import mypic from "../asset/Illustration.png";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const router = useRouter();
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="row">
        <div className="headline">
          <h2>Decide helps you to make Decicions as a team</h2>
        </div>
        <Image className="img" src={mypic} alt="Picture of the author" />
      </div>
    </div>
  );
};

export default Home;
